[project]
name = "mcpworks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.8"
dependencies = [
    "arxiv>=2.2.0",
    "mcp[cli]>=1.9.1",
    "pandas>=2.2.3",
    "pyarrow>=20.0.0",
]
